# Generated by Django 2.2.4 on 2019-08-29 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('event', '0002_auto_20190829_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=255)),
                ('no_of_tickets', models.FloatField()),
                ('service_fee', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='event.Event')),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows_seat_class', to='event.EventSeatClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
