# Generated by Django 2.2.4 on 2019-08-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='seat_class',
        ),
        migrations.AddField(
            model_name='bookings',
            name='seat_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows_seat_class', to='movie.Seat_Class'),
        ),
        migrations.RemoveField(
            model_name='show',
            name='screen',
        ),
        migrations.AddField(
            model_name='show',
            name='screen',
            field=models.ManyToManyField(blank=True, related_name='shows_screen', to='movie.Screen'),
        ),
    ]
