# Generated by Django 2.2.4 on 2019-08-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190828_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='screen',
        ),
        migrations.AddField(
            model_name='show',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows_screen', to='movie.Screen'),
        ),
    ]
