# Generated by Django 2.2.4 on 2019-08-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190828_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
